### ISSUE TITLE
Internal Module Missing

### ISSUE THREAD

**Issue by TheMerkyShadow** [manthey/pyexe#49]
import error: No module named 'modules_pyexe_list'

Please correct me if im wrong but isn't modules_pyexe.py
supposed to be modules_pyexe_list.py?

**Comment by manthey** [comment]
No, `modules_pyexe.py` can generate `modules_pyexe_list.py`.

`modules_pyexe.py` is used to *either* generate `modules_pyexe_list.py` *or* directly inject such a list into `pyexe.py`.  If you look at the appveyor.yml file, you'll see that it does the injection form.  For local testing the output and import form is sometimes more convenient, since it doesn't alter pyexe.py.

**Comment by TheMerkyShadow** [comment]
Ok that makes sense thanks for clairification @manthey

**Comment by manthey** [comment]
Thanks for asking -- I probably should document more of this (at least issues end up being a form of documentation).
